### ISSUE TITLE
rebel.xml generation includes directory that does not exist and misses source directories

### ISSUE THREAD

**Issue by skylarsutton** [zeroturnaround/maven-jrebel-plugin#15]
On WAR deployment, Jrebel warns me that the generated rebel.xml contains an invalid path. I agree with the warning, that path does not exist. The rebel.xml was generated with the jrebel-maven-plugin v1.1.5. I upgraded to v1.1.7 and confirmed the issue still exists. 

Interestingly, the generated rebel.xml only contains one directory (which doesn't exist) and misses dozen of source/resource directories elsewhere. 

I am able to work around this issue by manually specifying a lot of the configuration, but wanted to report it to you for future resolution. Something seems "off" in the generation process. 

> Invalid 'dir' defined in web link of rebel.xml (file:/C:/work/[my-company]/[my-project]/Tomcat/webapps/[our-app]/WEB-INF/classes/rebel.xml): Directory 'C:/work/[my-company]/[my-project]/Package/Web/src/main/webapp' does not exist

jrebel-maven-plugin configuration is:

```xml
<plugin>
	<groupId>org.zeroturnaround</groupId>
	<artifactId>jrebel-maven-plugin</artifactId>
	<version>1.1.7</version>
	<executions>
		<execution>
			<id>generate-rebel-xml</id>
			<phase>process-resources</phase>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

The generated rebel.xml is:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This is the JRebel configuration file. It maps the running application to your IDE workspace, enabling JRebel reloading for this project.
  Refer to https://manuals.zeroturnaround.com/jrebel/standalone/config.html for more information.
-->
<application generated-by="maven" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.zeroturnaround.com" xsi:schemaLocation="http://www.zeroturnaround.com http://update.zeroturnaround.com/jrebel/rebel-2_1.xsd">
	<classpath>
		<dir name="C:/work/[my-company]/[my-project]/Package/Web/target/classes">
		</dir>
	</classpath>

	<web>
		<link target="/">
			<dir name="C:/work/[my-company]/[my-project]/Package/Web/src/main/webapp">
			</dir>
		</link>
	</web>
</application>
```

**Comment by sander347** [comment]
Hi!

1) We managed to reproduce the plugin generating a "webapp" dir reference even when the directory itself does not exist in the project. I think we an just check for that and omit that - thanks for reporting!

2) You also mention many other resource directories being missing - can you pls contribute more details on this? As you might not want to post your logs or project structure to the public bug tracker, maybe you could send them with a more detailed description to support@zeroturnaround.com? Thanks!

--
Sander Sõnajalg
Product manager for JRebel tooling


(JIRA mirror - JR-7654)

**Comment by skylarsutton** [comment]
Thank you Sander - I sent an email to support to discuss this offline.
