### ISSUE TITLE
How to tell JRebel to use particular maven version .i am using maven 3 but still getting below error

### ISSUE THREAD

**Issue by tvteja** [zeroturnaround/maven-jrebel-plugin#17]
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error resolving version for 'org.zeroturnaround:jrebel-maven-plugin': Plugin requires Maven version 3.0
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch

**Comment by toomasr** [comment]
Do you mind sharing the section of the pom.xml where you include the JRebel Maven plugin? And as you are at it also `mvn --version`.

**Comment by tvteja** [comment]
Hi thanks for reply, i have added below dependency which mentioned in this link
https://manuals.zeroturnaround.com/jrebel/standalone/maven.html

and i am using maven version: 3.6.1 and thing is i am not sure how tell Jrebel (not sure is there any dependency or plugin for this) to use this maven 3.6.1

<plugin>
  <groupId>org.zeroturnaround</groupId>
  <artifactId>jrebel-maven-plugin</artifactId>
  <version>1.1.7</version> 
  <executions>
    <execution>
      <id>generate-rebel-xml</id>
      <phase>process-resources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
</plugin>

UPDATE: The project is running successfully on tomcat server(even without adding any dependencies). i faced issue when running with jetty only. when running with jetty i got same error as below

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error resolving version for 'org.zeroturnaround:jrebel-maven-plugin': Plugin requires Maven version 3.0

**Comment by Oja95** [comment]
Apologies for the lengthy response delay!

How are you executing your Maven commands? Are you running Maven through an IDE or command line?
If you're using an IDE, could you please make sure that the IDE's Maven settings are not configured to use Maven 2.x instead?

Could it be possible that the M2_HOME variable is pointing to a different Maven installation instead of the 3.2.1 version?

Does the same error occur when using the 1.1.5 version of the jrebel-maven-plugin instead? This version requires Maven 2.x instead.

**Comment by tvteja** [comment]
I have set Correct M2_HOME.(Checked from cmd prompt its showing correct version).
Maven Project using from Eclipse IDE.
However Its running fine from Tomcat sever Now. (jetty only issue).
We may close this issue.
Thanks for all responses.
close #17

**Comment by Oja95** [comment]
If using Eclipse, you could also install our JRebel IDE plugin via Marketplace. 
The Maven plugin should be used if it is not possible to use the IDE plugin for _rebel.xml_ configuration file generation.
